language: elixir

elixir:
  - 1.7.0

before_install:
  - wget https://github.com/contribsys/faktory/releases/download/v0.9.2-1/faktory_0.9.2-1_amd64.deb
  - sudo dpkg -i faktory_0.9.2-1_amd64.deb
  - faktory

script:
- mix test
